export const contractAddress = "0xa15bb66138824a1c7167f5e85b957d04dd34e468"

export const abi = [
   {
      "type":"constructor",
      "inputs":[
         {
            "name":"priceFeed",
            "type":"address",
            "internalType":"address"
         }
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"MINIMUM_USD",
      "inputs":[],
      "outputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"cheaperWithdraw",
      "inputs":[],
      "outputs":[],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"fund",
      "inputs":[],
      "outputs":[],
      "stateMutability":"payable"
   },
   {
      "type":"function",
      "name":"getAddressToAmountFunded",
      "inputs":[
         {
            "name":"fundingAddress",
            "type":"address",
            "internalType":"address"
         }
      ],
      "outputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"getFunder",
      "inputs":[
         {
            "name":"index",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         {
            "name":"",
            "type":"address",
            "internalType":"address"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"getOwner",
      "inputs":[],
      "outputs":[
         {
            "name":"",
            "type":"address",
            "internalType":"address"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"getPriceFeed",
      "inputs":[],
      "outputs":[
         {
            "name":"",
            "type":"address",
            "internalType":"contract AggregatorV3Interface"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"getVersion",
      "inputs":[],
      "outputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"withdraw",
      "inputs":[],
      "outputs":[],
      "stateMutability":"nonpayable"
   },
   {
      "type":"error",
      "name":"FundMe__NotOwner",
      "inputs":[]
   }
]